services:
  server:
    build: .
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3307" # Use host port 3307 to avoid conflict with the local MySQL instance