# Application Properties
spring:
  application:
    name: springsecurity
---
# Server Configuration
server:
  port: 8083
  servlet:
    session:
      timeout: 30m
---
# Spring Security
spring:
  security:
    user:
      name: admin
      password:
      roles: ADMIN

# Application Properties
---
spring:
  application:
    name: springsecurity

# Server Configuration
---
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

# Spring Security
---
spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Logging
---
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.example: DEBUG

# Thymeleaf
---
spring:
  thymeleaf:
    cache: false
    mode: HTML
